FROM golang:1-alpine3.20 AS builder

RUN apk add --no-cache git ca-certificates build-base su-exec olm-dev

COPY . /build
WORKDIR /build

RUN go build -o /usr/bin/mautrix-gvoice ./cmd/mautrix-gvoice

FROM alpine:3.20

ENV UID=1337 \
    GID=1337

RUN apk update
RUN apk add --no-cache ffmpeg su-exec ca-certificates olm bash jq yq-go curl chromium nss freetype freetype-dev harfbuzz nodejs npm \
&& rm -rf /var/cache/apk/*

RUN npm install -g puppeteer

ENV PUPPETEER\_SKIP\_CHROMIUM\_DOWNLOAD true

COPY --from=builder /usr/bin/mautrix-gvoice /usr/bin/mautrix-gvoice
COPY --from=builder /build/docker-puppeteer-run.sh /docker-puppeteer-run.sh
VOLUME /data

CMD ["/docker-puppeteer-run.sh"]
